/**
 * @file Describe the file
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * the const of table CalendarAlerts
 *
 * @since 2022-09-08
 */
export enum CalendarAlertsColumns {
  TABLE_NAME = 'CalendarAlerts',

  ID = '_id',

  EVENT_ID = 'event_id',

  EVENT_UUID = 'event_uuid',

  BEGIN = 'begin',

  END = 'end',

  ALARM_TIME = 'alarmTime',

  CREATION_TIME = 'creationTime',

  RECEIVED_TIME = 'receivedTime',

  NOTIFY_TIME = 'notifyTime',

  STATE = 'state',

  MINUTES = 'minutes',

  CREATOR = 'creator',

  TITLE = 'title',

  CONTENT = 'content',

  WANT_AGENT = 'wantAgent',

  BUTTONS = 'buttons',

  SLOT_TYPE = 'slotType',

  KEEP_HEADSUP = 'keepHeadsUp',

  TYPE = 'type',

  IDENTIFIER = 'identifier',

  RING_DURATION = 'ringDuration',

  CUSTOM_RING_URI = 'customRingUri',

  TIME_INTERVAL = 'timeInterval',

  SNOOZE_TIMES = 'snoozeTimes',

  SNOOZE_SLOT_TYPE = 'snoozeSlotType',

  SNOOZE_CONTENT = 'snoozeContent',

  EXPIRED_CONTENT = 'expiredContent',

  MAX_SCREEN_WANT_AGENT = 'maxScreenWantAgent',

  ACCOUNT_TYPE = 'account_type',

  ALL_DAY = 'allDay',

  NEED_AGENT = 'needAgent',

  UUID = 'uuid',
}